- name: ===================== Install Java =====================
  yum:
    name: java
  state: latest
  become: true

- name: ===================== Install libselinux-python =====================
  yum:
    name: libselinux-python
  state: latest
  become: true
