- name: ===================== Install Java =====================
  yum:    
    name: java
  state: latest
  become: yes

- name: ===================== Install libselinux-python =====================
  yum:
    name: "{{item.package}}"
    state: latest
  with_items: 
    - { package: 'libselinux-python' }
    - { package: 'unzip' }
  become: yes

- name: ===================== Check if directory '{{buildAgent_path}}' exists =====================
  file:
    path: '{{buildAgent_path}}'
    state: directory
    mode: 0755
  become: yes

- name: ===================== Download build agent =====================
  unarchive:
    src: "{{TeamCity_url}}/update/buildAgent.zip"
    dest: '{{buildAgent_path}}'
remote_src: yes
